blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Ideas
    url: https://github.com/yanthomasdev/lunaria/discussions/new?category=ideas
    about: Suggest an improvement you would like to see added to Lunaria
